apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: server
          image: kaybee97/player:v4
          ports:
            - containerPort: 8090
