apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: product
          image: kaybee97/product:v4.1
          ports:
            - containerPort: 8080
